
version: '3.4'

services:
  database:
    container_name: airdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: airdb
      POSTGRES_DB: airdb
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgresql://root:postgres@localhost:5432/airdb
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    image: postgres:14-alpine
    networks:
      - backnet

  backend:
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://root:postgres@database:5432/airdb
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - backnet
networks:
  backnet:
  frontnet:
